// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainingym.Context;

#nullable disable

namespace Trainingym.Migrations
{
    [DbContext(typeof(TrainingymContext))]
    partial class TrainingymContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trainingym.Models.Member", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MemberId"));

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("member_name");

                    b.HasKey("MemberId");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Trainingym.Models.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<long>("FkMemberid")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_memberid");

                    b.Property<long>("FkProductid")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_productid");

                    b.Property<DateTime>("OrderDateorder")
                        .HasColumnType("datetime2")
                        .HasColumnName("order_dateorder");

                    b.HasKey("OrderId");

                    b.HasIndex("FkMemberid");

                    b.HasIndex("FkProductid");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Trainingym.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("product_name");

                    b.HasKey("ProductId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Trainingym.Models.Order", b =>
                {
                    b.HasOne("Trainingym.Models.Member", "FkMember")
                        .WithMany("Orders")
                        .HasForeignKey("FkMemberid")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Member");

                    b.HasOne("Trainingym.Models.Product", "FkProduct")
                        .WithMany("Orders")
                        .HasForeignKey("FkProductid")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Product");

                    b.Navigation("FkMember");

                    b.Navigation("FkProduct");
                });

            modelBuilder.Entity("Trainingym.Models.Member", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Trainingym.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
